"""
tests/test_digital_fixtures.py

Issue #18 §5 — makes the digital-born golden fixtures actually gated.

`tests/fixtures/digital/make_fixtures.py` generates three deterministic fixtures and pins
their sha256s in `MANIFEST.json`. Before this module existed, nothing read either: the
fixture bytes are deliberately not committed, `--verify` compared regenerated bytes only
against on-disk bytes that were therefore never there, and no test invoked the generator.
The plan and digest both listed the fixtures as "✅ generated, sha256-pinned, `--verify`
mode" — all three claims were about code paths no CI or local run exercised.

What is pinned here:

  1. The generator is DETERMINISTIC — two runs in the same process produce identical bytes.
  2. Those bytes match the committed MANIFEST.json, so a change to the generator cannot
     land without the manifest being regenerated in the same commit.
  3. `--verify` returns 0 on agreement and non-zero on drift (it is the local pre-push
     check, so a silently-passing --verify is worse than none).
  4. The fixtures are STRUCTURALLY VALID, not merely stable: the PDFs' xref offsets resolve
     to their objects, and the DOCX opens in python-docx with the heading, the two-run
     paragraph, the 2x2 table and the page break the plan says it carries.
  5. `garbled.pdf` really is the Issue #10 construction — /WinAnsiEncoding declared, no
     /ToUnicode, cp1250 bytes in the content stream — because a fixture that quietly stopped
     reproducing the failure would make the decode-sanity gate untestable.

Everything writes to `tmp_path`; nothing here creates files in the repo.
"""

from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "digital"
GENERATOR = FIXTURE_DIR / "make_fixtures.py"
MANIFEST = FIXTURE_DIR / "MANIFEST.json"


@pytest.fixture(scope="module")
def make_fixtures():
    """The generator, imported by path — it is a script, not an installed module."""
    spec = importlib.util.spec_from_file_location("make_fixtures", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def blobs(make_fixtures):
    return make_fixtures.build_all()


# ── determinism and the manifest ─────────────────────────────────────────────


def test_generator_is_deterministic(make_fixtures):
    """Two runs, identical bytes. The premise of every other assertion here."""
    first, second = make_fixtures.build_all(), make_fixtures.build_all()
    assert sorted(first) == sorted(second)
    for name in first:
        assert first[name] == second[name], f"{name} is not byte-reproducible"


def test_docx_is_not_deflated(blobs):
    """DEFLATE output depends on the linked zlib, so a byte-pinned zip must be STORED.

    Guards the specific regression: switching back to ZIP_DEFLATED would still produce a
    valid .docx and still pass a same-machine `--verify`, then drift on a zlib upgrade.
    """
    with zipfile.ZipFile(io.BytesIO(blobs["minimal.docx"])) as zf:
        for info in zf.infolist():
            assert info.compress_type == zipfile.ZIP_STORED, info.filename
            assert info.create_system == 3, f"{info.filename}: create_system must be pinned"
            assert info.date_time == (1980, 1, 1, 0, 0, 0), info.filename


def test_generated_bytes_match_committed_manifest(blobs):
    """The manifest is the reviewable stand-in for binaries that are not committed."""
    recorded = json.loads(MANIFEST.read_text(encoding="utf-8"))
    assert sorted(recorded) == sorted(blobs), "MANIFEST.json and the builders disagree"
    for name, data in blobs.items():
        assert recorded[name]["sha256"] == hashlib.sha256(data).hexdigest(), (
            f"{name} changed without MANIFEST.json being regenerated — run "
            f"`python tests/fixtures/digital/make_fixtures.py` and review the diff"
        )
        assert recorded[name]["bytes"] == len(data), name


def test_verify_mode_passes_against_the_committed_manifest():
    proc = subprocess.run(
        [sys.executable, str(GENERATOR), "--verify"],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr


def test_verify_mode_fails_on_manifest_drift(tmp_path, blobs, make_fixtures):
    """A --verify that cannot fail is not a check."""
    tampered = make_fixtures.manifest_for(blobs)
    tampered["minimal.pdf"]["sha256"] = "0" * 64
    (tmp_path / "MANIFEST.json").write_text(json.dumps(tampered), encoding="utf-8")

    proc = subprocess.run(
        [sys.executable, str(GENERATOR), "--verify", "--outdir", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode != 0
    assert "minimal.pdf" in proc.stderr and "DRIFT" in proc.stderr


def test_manifest_lives_beside_the_fixtures_it_describes(make_fixtures, tmp_path):
    """It was committed one directory up from where the generator writes it, so running the
    generator produced a second manifest and left the committed one permanently stale."""
    assert MANIFEST.parent == FIXTURE_DIR
    assert not (FIXTURE_DIR.parent / "MANIFEST.json").exists()
    make_fixtures.main(["--outdir", str(tmp_path)])
    assert (tmp_path / make_fixtures.MANIFEST_NAME).exists()


# ── the fixtures are structurally real ───────────────────────────────────────


@pytest.mark.parametrize("name", ["minimal.pdf", "garbled.pdf"])
def test_pdf_xref_offsets_resolve(blobs, name):
    """Every xref entry must point at its own `N 0 obj`, or a real parser rejects the file.

    Checked by hand rather than with a PDF library on purpose: the generator hand-rolls the
    xref table precisely because no library gives byte determinism, so the arithmetic is the
    part that can break — and it differs between the 1-page and 2-page layouts.
    """
    data = blobs[name]
    start = int(re.search(rb"startxref\s+(\d+)", data).group(1))
    assert data[start : start + 5] == b"xref\n"
    header = re.search(rb"xref\n0 (\d+)\n", data[start:])
    size = int(header.group(1))
    body = data[start + header.end() :]
    entries = re.findall(rb"(\d{10}) (\d{5}) ([nf])", body)[:size]
    assert len(entries) == size
    for num, (offset, _gen, kind) in enumerate(entries):
        if kind == b"f":
            continue
        assert data[int(offset) :].startswith(f"{num} 0 obj".encode()), (
            f"{name}: xref entry {num} points at the wrong offset"
        )


def test_minimal_pdf_has_two_pages_and_three_blocks(blobs):
    data = blobs["minimal.pdf"]
    assert data.startswith(b"%PDF-1.4\n")
    assert b"/Count 2" in data
    assert data.count(b"BT\n") == 3, "three separate text blocks are the group_id assertion"
    # No /Info, no /ID, no dates — that is what makes the bytes reproducible.
    assert b"/CreationDate" not in data and b"/ID" not in data


def test_garbled_pdf_is_the_issue_10_construction(blobs):
    """WinAnsi declared, no /ToUnicode, cp1250 bytes. Extraction succeeds and lies."""
    data = blobs["garbled.pdf"]
    assert b"/WinAnsiEncoding" in data
    assert b"/ToUnicode" not in data, "a /ToUnicode map would make the text decode correctly"
    # 'sondě' in cp1250 puts 0xEC where WinAnsi has 'ì' — the systematic, not random, failure.
    assert "sondě".encode("cp1250") in data
    assert "sondě".encode("utf-8") not in data


def test_minimal_docx_opens_and_carries_the_documented_structure(blobs, tmp_path):
    docx = pytest.importorskip("docx", reason="python-docx is an optional digital-stack dep")
    path = tmp_path / "minimal.docx"
    path.write_bytes(blobs["minimal.docx"])
    document = docx.Document(str(path))

    styles = [p.style.name for p in document.paragraphs]
    assert "Heading 1" in styles, "the heading is what lines[].style.heading_level maps from"

    # Two runs in ONE paragraph: the adapter must emit these as one group_id, not two.
    two_run = [p for p in document.paragraphs if p.text.startswith("První odstavec")]
    assert len(two_run) == 1 and len(two_run[0].runs) == 2

    assert len(document.tables) == 1
    assert [[c.text for c in row.cells] for row in document.tables[0].rows] == [
        ["Vrstva", "Mocnost"],
        ["Ornice", "30 cm"],
    ]
    # An explicit page break, so pages[] boundaries are testable without a renderer.
    assert 'w:type="page"' in document.element.xml or "page" in document.element.xml

    # Fixed dates, or the fixture would not be reproducible.
    assert document.core_properties.created.year == 1980
